### ISSUE TITLE
The Newest versions seem to crash on NeoForge Servers

### ISSUE THREAD

**Issue by IvorAmlug** [willatendo/Fossils-And-Archaeology-Legacy#21]
My server using NeoForge 1.21.1-21.1.90
Always crashes on startup versions prior to 1.4 didnt crash.

A crashlog  from the server:
[Uploading crash-2024-12-17_10.17.05-fml.txt…]()
I hopefully just temporarly downgraded to 1.3.2 again

**Comment by willatendo** [comment]
Fixed!
